version: '3.9'

services:
  api-service:
    container_name: api-container
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    networks:
      - backend



networks:
  backend:
    driver: bridge



